### ISSUE TITLE
Can't access Script.stderr for captured scripts

### ISSUE THREAD

**Issue by passsy** [google/dart_cli_script#37]
Depending on the script that gets executed, the `stderr` can be accessed or not.

```dart
  test("allows capture", () async {
    var script =
        Script.capture((_) async => await Script('someProgram').exitCode);
    final text = await script.stderr.text;
    // Error in someProgram:
    // ProcessException: No such file or directory
    // Command: someProgram 
    expect(text, contains('someProgram'));
  });

  test("fails", () async {
    var script =
        Script.capture((_) async => await Script('which someProgram').exitCode);
    final text = await script.stderr.text;
    expect(text, contains('someProgram'));
    // Expected: contains 'someProgram'
    // Actual: ''
  });
```

The only difference is that the first test runs `someProgram` the second `which someProgram`. 

The first script throws `ProcessException` internally. The second parses the non-zero exit code and throws `ScriptException` and does not pipe the streams to Stream.capture via

https://github.com/google/dart_cli_script/blob/d5bd0285c3d3c8cb18684ee3295207f308234d46/lib/src/script.dart#L453-L456

**Comment by nex3** [comment]
The difference here is that the first script is wrapping a Dart exception that's thrown by `Process.start()`, which gets converted into a script failure that prints the text of the exception to stderr, while the second directly exposes the results of `which someProgram` (that is to say, printing no output and returning exit code 1).
