### ISSUE TITLE
Doesn't work with environment variables

### ISSUE THREAD

**Issue by lukepighetti** [google/dart_cli_script#42]
```dart
run(r'echo $PATH');
```

outputs

```
$PATH
```

instead of my actual environment variable path

```
usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin
```

**Comment by nex3** [comment]
Yes, you need to explicitly inject variables (environment or otherwise) into your script arguments. You can either write `run('echo', args: [env('PATH')])` or `run('echo ${arg(env('PATH'))}')`.
