### ISSUE TITLE
How to kill a running script?

### ISSUE THREAD

**Issue by appinteractive** [google/dart_cli_script#48]
A Process can be killed with Process().kill() but how can I kill a Script? I have the isse that when I close the app, my interactive script still runs so I need a way to kill it before leaving the app.

**Comment by nex3** [comment]
We added support for `Script.kill()` in 0.3.0... but then forgot to release it :sweat_smile:. It's published now.

**Comment by appinteractive** [comment]
uhhh nice have much thanks :*
