### ISSUE TITLE
Different results with real terminal for double quotes searchs

### ISSUE THREAD

**Issue by devibrahimkarahan** [google/dart_cli_script#53]
Im trying to find files that contains **referrer: "**. (include " (double quotes))

This is my code that works in terminal
`mdfind 'kMDItemTextContent="referrer: \"*"' -onlyin lib/`
There is a one file with referrer: "  text

But when i tried to use it inside Script like this, im getting all files (12 files) that contains referrer:  (not include double quotes version)
`Script(r'''mdfind 'kMDItemTextContent="referrer: \"*"' -onlyin lib/''')`

I also tried all of these
`Script(r'''mdfind 'kMDItemTextContent="referrer: "*"' -onlyin lib/''')`
`Script("mdfind 'kMDItemTextContent="referrer: "*"' -onlyin lib/")`
`Script("mdfind 'kMDItemTextContent=referrer: \"*' -onlyin lib/")`

As i say, it works in normal terminal, is there any problem with script or package?

MacOS 13.0 M1
flutter doctor -v
```
[✓] Flutter (Channel stable, 3.7.6, on macOS 13.0 22A380 darwin-arm64, locale tr)
    • Flutter version 3.7.6 on channel stable at /Users/appnation/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12cb4eb7a0 (9 weeks ago), 2023-03-01 10:29:26 -0800
    • Engine revision ada363ee93
    • Dart version 2.19.3
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/appnation/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 71.0.5
    • Dart plugin version 222.4459.16

[✓] VS Code (version 1.77.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • iPhone 11 (mobile) • 00008030-001675310E91802E • ios            • iOS 16.3.1 20D67
    • macOS (desktop)    • macos                     • darwin-arm64   • macOS 13.0 22A380 darwin-arm64
    • Chrome (web)       • chrome                    • web-javascript • Google Chrome 112.0.5615.137
    ! Error: (null) needs to connect to determine its availability. Check the connection between the device and its companion iPhone, and the connection between the iPhone and Xcode. Both devices may also
      need to be restarted and unlocked. (code 1)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

**Comment by nex3** [comment]
All of your argument strings parse as `["mdfind", 'kMDItemTextContent="referrer: "*"', '-onlyin', 'lib/']`, except for `"mdfind 'kMDItemTextContent=referrer: \"*' -onlyin lib/"` which parses as `["mdfind", 'kMDItemTextContent=referrer: "*', "-onlyin'" "lib/"]`. (You can check the parsing directly yourself using the internal [`CliArgument.parse()`](https://github.com/google/dart_cli_script/blob/31b1169a393e811e46b18309c9478c64a1ed9a5b/lib/src/cli_arguments.dart#L40-L58) function.) This is all expected, which makes me think either the `mdfind` command isn't parsing its input how you expect, or Dart's `Process` API itself is interpreting arguments in an unusual way.
