### ISSUE TITLE
stdout not drained when exitCode completes

### ISSUE THREAD

**Issue by passsy** [google/dart_cli_script#59]
The following test demonstrates that stdout is not completely drained when the `exitCode` completes.

```dart
import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:cli_script/cli_script.dart';
import 'package:test/fake.dart';
import 'package:test/test.dart';

void main() {
  test('issue57', () async {
    final fakeStdout = FakeStdoutStream();
    await overrideIoStreams(
      body: () async {
        final script = Script(
          'echo',
          args: ['hello'],
        );
        await script.exitCode;

        // removing this line makes the test fail
        await Future(() {});
      },
      stdout: () {
        return fakeStdout;
      },
    );
    expect(fakeStdout.lines, ['hello\n']);
  });
}

class FakeStdoutStream with Fake implements Stdout {
  final List<List<int>> _writes = <List<int>>[];

  List<String> get lines => _writes.map(utf8.decode).toList();

  @override
  void add(List<int> bytes) {
    _writes.add(bytes);
  }

  @override
  void writeln([Object? object = ""]) {
    _writes.add(utf8.encode('$object'));
  }

  @override
  void write(Object? object) {
    _writes.add(utf8.encode('$object'));
  }

  @override
  void writeAll(Iterable objects, [String sep = ""]) {
    _writes.add(utf8.encode(objects.join(sep)));
  }

  @override
  void writeCharCode(int charCode) {
    _writes.add(utf8.encode(String.fromCharCode(charCode)));
  }

  @override
  bool get supportsAnsiEscapes => false;
}

T overrideIoStreams<T>({
  required T Function() body,
  Stdin Function()? stdin,
  Stdout Function()? stdout,
  Stdout Function()? stderr,
}) {
  return runZoned(
    () => IOOverrides.runZoned(
      body,
      stdout: stdout,
      stdin: stdin,
      stderr: stderr,
    ),
    zoneSpecification: ZoneSpecification(
      print: (self, parent, zone, line) {
        final override = IOOverrides.current;
        override?.stdout.writeln(line);
      },
    ),
  );
}

```

Adding `await Future(() {});` makes `stdout` write the echo. It is still unclear whether waiting one event loop is always enough, or if it is just a lucky guess.

**Expected**

`stdout` and `stderr` are completely drained when `exitCode` completes.

**Actual**

`stdout` and `stderr` continue to write after `exitCode` completes.

--- 

Comparison:

[`dcli`](https://github.com/onepub-dev/dcli/blob/b3f3ba8d69c5eb2aaea1cfdaa62a65ecba3b9239/dcli/lib/src/util/runnable_process.dart#L484-L488) waits for `stdout` and `stderr` to complete before returning `exitCode`.

**Comment by nex3** [comment]
This is intended (and documented!) behavior. Among the [`Script`](https://pub.dev/documentation/cli_script/latest/cli_script/Script-class.html) class's guarantees is:

> Once [done](https://pub.dev/documentation/cli_script/latest/cli_script/Script/done.html) completes, [stdout](https://pub.dev/documentation/cli_script/latest/cli_script/Script/stdout.html) and [stderr](https://pub.dev/documentation/cli_script/latest/cli_script/Script/stderr.html) will emit done events immediately afterwards (modulo a few microtasks).

That "modulo" is important! If you remove `await new Future(() {})`, your test has a race condition between the final microtasks of the `Script` completing and the microtasks necessary for the test case to reach `expect(fakeStdout.lines, ['hello\n']);`. Notably, there is _not_ a guarantee that `stdout` emits a `done` event _before_ `exitCode` completes.

**Comment by passsy** [comment]
> This is intended (and documented!) behavior.

You're right!
But is it useful? Would `dart_cli_script` be easier to use if `exitCode` and `done` would wait for the completion of `stdout` and `stderr` before completing? Is there any benefit of the current behaviour?

I would like to have a `Script` API that notifies me when everything is finished and closed. This would allow me to overcome my race condition. `.done` feels like it is the correct method to accomplish this.
`await Future((){});` does not feel like an official way. 

### Delay `.done` by one macrotask

Adding the delay, would make `done` more predictable. After completion, pipes could be guaranteed to be closed. 
It would also make the API more future-proof, in case it requires two macrotasks at some point in the future.

```diff
    exitCode.then((code) async {
      if (_doneCompleter.isCompleted) return;

+      await Future(() {});
      if (code == 0) {
        debug("[$name] exited with exit code 0");
        _doneCompleter.complete(null);
      } else {
        debug("[$name] exited with exit code $code");
        _doneCompleter.completeError(
            ScriptException(name, code), StackTrace.current);
      }

      _closeOutputStreams();
      _extraStderrController.close();
      _stdinCloser.close();
    }, onError: _handleError);
```

Adding the macrotask would also make `Script.kill()` more predictable, always returning `false` after `done` completed.
See `interrupts pipe` test (the only one failing), which requires one implicit macrotask (`await lines.toList()`) after `script.done` before `kill()` returns false. 

```diff
    test('interrupts pipe', () async {
      var controller = StreamController<List<int>>();
      var completer = Completer<void>();
      var script = controller.stream | _watchSignalsAndStdin(completer);
      var lines = script.stdout.lines;

      controller.sink.add(utf8.encode('before'));
      await pumpEventQueue();

      expect(script.kill(), true);
      await pumpEventQueue();

      controller.sink.add(utf8.encode('after'));
      await pumpEventQueue();

      expect(script.kill(), true);
      await pumpEventQueue();

      completer.complete();
      expect(script.done, throwsScriptException(143));
      expect(await lines.toList(), [
        'from a: before',
        'b: SIGTERM',
        'b: bye!',
      ]);

+      await script.done.catchError((_) {});
      expect(script.kill(), false);
    });
```

With the additional delay, the test can use `await script.done.catchError((_) {});` before the final assertion `expect(script.kill(), false);` to explicitly reach the correct state.

**Comment by nex3** [comment]
Your proposed fix introduces a new race condition: if `_doneCompleter` is completed during the added padding macrotask, it would end up double-completing. That's certainly fixable, but it does illustrate that messing around with task ordering without having explicit data dependency paths is _very_ error-prone. Even if we did provide a completion-order guarantee, it would be a very bad idea to rely on it.

I'm skeptical just adding a macrotask wait would _actually_ provide as strong a guarantee as you want it to. Asynchronous programming is complex, full of timing-dependent edge cases, and difficult to reason about, so I'm generally more comfortable providing a looser guarantee that pushes users to explicitly set up future chains rather than relying on implicit timings.
