### ISSUE TITLE
check function needs to handle stdin

### ISSUE THREAD

**Issue by bsutton** [google/dart_cli_script#9]
The check function isn't allowing stdin to be processed by the called script.

I've not tested but this may be a problem for output and lines as well.

**Comment by nex3** [comment]
I'm not sure how it would handle stdin... the return value is a `bool`, so there's nothing for the stdin to attach to. If the user wanted to do something more complex, I'd expect them to use `Script` directly, as in `(Script(...) | Script(...)).success` or

```dart
var script = Script(...);
script.stdin.writeln(...);
if (await script.success) {
  // ...
}
```
